/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.base.ui;

import GameWorld.World;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;

/**
 * @version 1.0
 */
public class GamePanel extends javax.swing.JPanel implements GameSection
{
    private World world;
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() 
    {        
        initComponents();
    }

    public void setWorld(World world) {
        this.world = world;
        
    }
    /**
     * pinta el panel
     * @param g graphics
     */
    @Override
    public void paint(Graphics g)
    {
        if(world != null){
            world.paint(g);
               }
        else
            System.err.println("[GAMEPANEL.PAINT] World is null!");
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(world.getWidth(), world.getHeight());
    }
    /**
     * actualiza el juego
     */
    @Override
    public void update() 
    {
       this.repaint();
    }

    @Override
    public Rectangle getBoundaries() {
        return getBounds();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
